version: 1.15.{build}
image: Visual Studio 2022
before_build:
  - git submodule update -q --init --recursive
  - cmd: |
      if /i %platform% equ x86 msbuild "libsodium\builds\msvc\vs2022\libsodium.sln" "/p:Configuration=Ltcg%configuration%;Platform=Win32" /m
      if /i %platform% equ x64 msbuild "libsodium\builds\msvc\vs2022\libsodium.sln" "/p:Configuration=Ltcg%configuration%;Platform=x64"   /m
  - nuget restore -Verbosity quiet
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64
build:
  project: eduLibsodium.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)
